### ISSUE TITLE
chore: Add data guideline for participants

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/tutorials#97] opened 2024-06-13 18:17 UTC
Yesterday after eScience team meeting, it was brought up that we currently do not have any guidelines for participants that wants to bring their own data. This involves how much data can they bring and play with locally or in codespaces.

**Comment by vanitech** [comment] 2024-06-13 22:38
Dupe of #51

**Closed** 2024-06-14 17:46 UTC
Labels: duplicate, todo
